### PR TITLE
add overlay support

### PR DESCRIPTION
**Pull request by lukka**

### CODE REVIEW

**Comment by vadi2** [comment]
How would I test this in my action?

**Comment by lukka** [comment]
> How would I test this in my action?

you could try to use `lukka/run-vcpkg@overlay_support`in your workflow.

**Comment by vadi2** [comment]
It would seem it worked on the first go? A bit strange how it found the Lua overlay port cache already, but I'll take it! https://github.com/vadi2/Mudlet/runs/591434437?check_suite_focus=true

**Comment by lukka** [comment]
@vadi2 the explanation is that the previous run cached the right version of lua, then the next run when running `vcpkg remove --outdated` was going to uninstall it, and then `vcpkg install --overlay-ports=lua` was going to install it again. The fix is to "force passing" `--overlay-ports=` to all vcpkg invocations. Thanks for confirming the fix!

**Pull request merged**
