### PR TITLE
Enable windows CI testing again and use the 2020.06 release of…

### PR DESCRIPTION
**Pull request by jwillemsen**
… vcpkg

    * .github/workflows/build-test.yml:

### CODE REVIEW

**Comment by lukka** [comment]
Thanks! Is the original vcpkg's bootstrap failure fixed in most recent vcpkg?

**Comment by lukka** [comment]
This PR addresses https://github.com/lukka/run-vcpkg/issues/1

**Comment by jwillemsen** [comment]
The log of issue #1 is not accessible anymore. vcpkg does work correctly not on Windows when I check the action of this PR

**Comment by lukka** [comment]
@jwillemsen 

> The log of issue #1 is not accessible anymore. vcpkg does work correctly not on Windows when I check the action of this PR

@jwillemsen guess you meant "work correctly **now**", right? :)

**Comment by jwillemsen** [comment]
Yes

**Pull request merged**
